definitions:
  CarSaleAd-Web-Api_api_dto.CityResponse:
    properties:
      country:
        $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.CountryResponse'
      id:
        type: integer
      name:
        type: string
    type: object
  CarSaleAd-Web-Api_api_dto.CountryResponse:
    properties:
      cities:
        items:
          $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.CityResponse'
        type: array
      id:
        type: integer
      name:
        type: string
    type: object
  CarSaleAd-Web-Api_api_dto.CreateUpdateCountryRequest:
    properties:
      name:
        maxLength: 20
        minLength: 3
        type: string
    required:
    - name
    type: object
  CarSaleAd-Web-Api_api_dto.Filter:
    properties:
      filterType:
        type: string
      from:
        type: string
      to:
        type: string
      type:
        type: string
    type: object
  CarSaleAd-Web-Api_api_dto.GetOtpRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - mobileNumber
    type: object
  CarSaleAd-Web-Api_api_dto.LoginByUsernameRequest:
    properties:
      password:
        minLength: 6
        type: string
      username:
        minLength: 5
        type: string
    required:
    - password
    - username
    type: object
  CarSaleAd-Web-Api_api_dto.PagedList-CarSaleAd-Web-Api_api_dto_CountryResponse:
    properties:
      hasNextPage:
        type: boolean
      hasPreviousPage:
        type: boolean
      items:
        items:
          $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.CountryResponse'
        type: array
      pageNumber:
        type: integer
      totalPages:
        type: integer
      totalRows:
        type: integer
    type: object
  CarSaleAd-Web-Api_api_dto.PaginationInputWithFilter:
    properties:
      filter:
        additionalProperties:
          $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.Filter'
        type: object
      pageNumber:
        type: integer
      pageSize:
        type: integer
      sort:
        items:
          $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.Sort'
        type: array
    type: object
  CarSaleAd-Web-Api_api_dto.RegisterLoginByMobileRequest:
    properties:
      mobileNumber:
        maxLength: 11
        minLength: 11
        type: string
      otp:
        maxLength: 6
        minLength: 6
        type: string
    required:
    - mobileNumber
    - otp
    type: object
  CarSaleAd-Web-Api_api_dto.RegisterUserByUsernameRequest:
    properties:
      email:
        minLength: 6
        type: string
      firstName:
        minLength: 3
        type: string
      lastName:
        minLength: 6
        type: string
      password:
        minLength: 6
        type: string
      username:
        minLength: 6
        type: string
    required:
    - firstName
    - lastName
    - password
    - username
    type: object
  CarSaleAd-Web-Api_api_dto.Sort:
    properties:
      col_id:
        type: string
      sort:
        type: string
    type: object
  CarSaleAd-Web-Api_api_helper.BaseHttpResponse:
    properties:
      error: {}
      result: {}
      resultCode:
        type: integer
      success:
        type: boolean
      validationErrors:
        items:
          $ref: '#/definitions/CarSaleAd-Web-Api_api_validations.ValidationError'
        type: array
    type: object
  CarSaleAd-Web-Api_api_validations.ValidationError:
    properties:
      message:
        type: string
      property:
        type: string
      tag:
        type: string
      value:
        type: string
    type: object
  api_handlers.personData:
    properties:
      first_name:
        maxLength: 10
        minLength: 4
        type: string
      last_name:
        maxLength: 20
        minLength: 6
        type: string
      mobile_number:
        maxLength: 11
        minLength: 11
        type: string
    required:
    - first_name
    - last_name
    - mobile_number
    type: object
info:
  contact: {}
paths:
  /v1/countries/:
    post:
      consumes:
      - application/json
      description: Create a Country
      parameters:
      - description: Create a Country
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.CreateUpdateCountryRequest'
      responses:
        "201":
          description: Country response
          schema:
            allOf:
            - $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.CountryResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Create a Country
      tags:
      - Country
  /v1/countries/{id}:
    delete:
      consumes:
      - application/json
      description: Delete a Country
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Response
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Delete a Country
      tags:
      - Country
    get:
      consumes:
      - application/json
      description: Get a Country
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: Country Response
          schema:
            allOf:
            - $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.CountryResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Get a Country
      tags:
      - Country
    put:
      consumes:
      - application/json
      description: Update a Country
      parameters:
      - description: Id
        in: path
        name: id
        required: true
        type: integer
      - description: Update a Country
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.CreateUpdateCountryRequest'
      responses:
        "200":
          description: Country response
          schema:
            allOf:
            - $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.CountryResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Update a Country
      tags:
      - Country
  /v1/countries/get-by-filter:
    post:
      consumes:
      - application/json
      description: Get Countries
      parameters:
      - description: Request
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.PaginationInputWithFilter'
      responses:
        "200":
          description: Country Response
          schema:
            allOf:
            - $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
            - properties:
                result:
                  $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.PagedList-CarSaleAd-Web-Api_api_dto_CountryResponse'
              type: object
        "400":
          description: Bad request
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: Get Countries
      tags:
      - Country
  /v1/health/:
    get:
      consumes:
      - application/json
      description: Test Health
      produces:
      - application/json
      responses:
        "200":
          description: Done
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
      summary: Health Test
      tags:
      - Health
  /v1/test/binder/body:
    post:
      consumes:
      - application/json
      description: Test BodyBinder
      parameters:
      - description: person data
        in: body
        name: person
        required: true
        schema:
          $ref: '#/definitions/api_handlers.personData'
      produces:
      - application/json
      responses:
        "200":
          description: Done
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
      security:
      - AuthBearer: []
      summary: BodyBinder
      tags:
      - Test
  /v1/test/user/{id}:
    get:
      consumes:
      - application/json
      description: Test UserById
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Done
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
      summary: UserById
      tags:
      - Test
  /v1/users/login-by-mobile:
    post:
      consumes:
      - application/json
      description: RegisterLoginByMobileNumber
      parameters:
      - description: RegisterLoginByMobileRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.RegisterLoginByMobileRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Done
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
      summary: RegisterLoginByMobileNumber
      tags:
      - User
  /v1/users/login-by-username:
    post:
      consumes:
      - application/json
      description: LoginByUsername
      parameters:
      - description: LoginByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.LoginByUsernameRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Done
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
      summary: LoginByUsername
      tags:
      - User
  /v1/users/register-by-username:
    post:
      consumes:
      - application/json
      description: RegisterByUsername
      parameters:
      - description: RegisterUserByUsernameRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.RegisterUserByUsernameRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Done
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
      summary: RegisterByUsername
      tags:
      - User
  /v1/users/send-otp:
    post:
      consumes:
      - application/json
      description: Test SendOtp
      parameters:
      - description: GetOtpRequest
        in: body
        name: Request
        required: true
        schema:
          $ref: '#/definitions/CarSaleAd-Web-Api_api_dto.GetOtpRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Done
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
        "400":
          description: Failed
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
        "409":
          description: Failed
          schema:
            $ref: '#/definitions/CarSaleAd-Web-Api_api_helper.BaseHttpResponse'
      summary: SendOtp to user
      tags:
      - User
securityDefinitions:
  AuthBearer:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
